### ISSUE TITLE
Missing info on listsing page

### ISSUE THREAD

**Issue by siemvaessen** [zimmerman-team/open-UN-Habitat#14]
The following info is missing: 

Countries:Kenya, Uganda, Sudan, Tanzania
Sectors:Reform, Water, Agericultural Development,

This block resides on the same level as CLEAR SEARCH (see:http://staging.verviant.com/concepts/Open-UNH/HTML/vs2/searchresults.php?searchword=)

**Comment by kradoslavov** [comment]
Cannot reproduce it, the block appears when there is a filter selection

**Comment by siemvaessen** [comment]
roger that.
