### ISSUE TITLE
URL fix

### ISSUE THREAD

**Issue by siemvaessen** [zimmerman-team/open-UN-Habitat#18]
Currently http://unhabitat.openaidsearch.org/sample-page/?id=41120-1913&back_url=%2F%3Fs%3D

is the URL with /sample-page/ in it.

Please change /sample-page/  to /search/

**Comment by kradoslavov** [comment]
there is some redirect in the WP admin, for page_id=2 to go to /sample-page/

**Comment by siemvaessen** [comment]
Ah. will look into WP-thing.

**Comment by siemvaessen** [comment]
Fixed in WP. (was a page that had a different name.)
