### ISSUE TITLE
AJAX error

### ISSUE THREAD

**Issue by siemvaessen** [zimmerman-team/open-UN-Habitat#19]
I can reproduce AJAX error:

Go to results, go to detail, SWIPE with trackpad (mac) and AJAX error pops up. If I do not use SWIPE but BACK TO SEARCH RSULTS button, it is fine.

**Comment by kradoslavov** [comment]
Cannot reproduce on Windows machine. What is the SWIPE doing exactly?

**Comment by siemvaessen** [comment]
cannot reproduce with SWIPE anymore. Well, we'll keep this one in mind in case it pops up.
