### ISSUE TITLE
Related projects | IATI compliant namespace?

### ISSUE THREAD

**Issue by siemvaessen** [zimmerman-team/open-UN-Habitat#27]
For UN-H we have interface space for Related Projects. Can this be related to http://iatistandard.org/codelists/related_activity_type ?

Or is this typically non IATI?

**Comment by Hedde** [comment]
Related activities are not implemented at the moment. The field wasn't available or even IATI compliant during OIPA V1 nor do any of the publishers seem to use it in their sets. However extending the current parser with related activities is straight forward, and will probably only require an hour of coding, testing and pushing to the live environment.

For an exact description how this should be implemented and used, relate to:
http://iatistandard.org/activities-standard/related-documents/related-activity
