### ISSUE TITLE
Check HTML margins and placement of elements

### ISSUE THREAD

**Issue by siemvaessen** [zimmerman-team/open-UN-Habitat#3]
Check HTML margins and placement of elements
‘View results as’ element: margins not correct – see Wordpress templates
‘Sort by’ element: right aligned

**Comment by siemvaessen** [comment]
Check: http://staging.verviant.com/concepts/Open-UNH/HTML/vs2/searchresults.php?searchword= for correct allignment.

**Comment by kradoslavov** [comment]
Fixed

**Comment by siemvaessen** [comment]
‘Sort by’ element: right aligned NOT yet fixed.?
