### ISSUE TITLE
Set sector to real name, not code

### ISSUE THREAD

**Issue by siemvaessen** [zimmerman-team/open-UN-Habitat#35]
Sector: 43030

Should be:

Sector: [Name of sector]  in this case only one: Urban development and Management

**Comment by kradoslavov** [comment]
This seems to be a problem with the API, for all of the activities the returned sectors is as follows:
"activity_sectors": [{"code": "43030", "name": "43030", "percentage": null}]

**Comment by Hedde** [comment]
I will have a look at this tomorrow

**Comment by Hedde** [comment]
I cannot replicate this issue, both the Activity and Sector resources represent a sector name and code value. This is possibly a XML flaw.

**Comment by kradoslavov** [comment]
I still see the same result with the following query:
http://oipa.openaidsearch.org/api/v2/activities/?format=json&organisations=41120&limit=20
