### ISSUE TITLE
How to echo URI using whistleblower

### ISSUE THREAD

**Issue by siemvaessen** [zimmerman-team/open-UN-Habitat#38]
How to echo URI using whistleblower?

Go to either:

Listing: http://unhabitat.openaidsearch.org/?s=&countries=AF

Or detail: http://unhabitat.openaidsearch.org/search/?id=41120-1958&back_url=%2F%3Fs%3D%26countries%3DAF

And click Whistleblower. The URI needs to be added to the form request (hidden)

What is the best way to go about this?

Siem

**Comment by kradoslavov** [comment]
I guess pass the URI in the URL to the whistblower page.
Other option is to set a cookie withe the URI and in the whistleblower page to read it and clear the cookie.
