### ISSUE TITLE
Term Palestine not found

### ISSUE THREAD

**Issue by siemvaessen** [zimmerman-team/open-UN-Habitat#39]
There is a project: http://unhabitat.openaidsearch.org/?page_id=2&id=41120-1913&back_url=?s=&countries=WW

TItle:

Towards Sustainable Solutions for Improved Living Conditions of Palestine Refugees in Lebanon

Query input search: Palestine Refugees = 1 result

Query input search: Palestine  = 0 results

**Comment by kradoslavov** [comment]
It is strange but this is what the API returns:
http://oipa.openaidsearch.org/api/v2/activities/?format=json&organisations=41120&limit=20&offset=0&query=Palestine

http://oipa.openaidsearch.org/api/v2/activities/?format=json&organisations=41120&limit=20&offset=0&query=Palestine%20Refugees

So I think that the API splits the query by space and searches for the words separately, so in this case it finds one activity for the query 'Refugees'

**Comment by Hedde** [comment]
I thought of a better implementation, this should work fine now
