### ISSUE TITLE
Project detail page

### ISSUE THREAD

**Issue by kenek15** [zimmerman-team/open-UN-Habitat#55]
Document title should show, not name of the file
Commitments not showing as well - at least for the project at this location: http://unhabitat.openaidsearch.org/search/?id=41120-9999&back_url=%2F%3Fs%3D

**Comment by siemvaessen** [comment]
No doc names are available in the dataset, hence filename is being rendered.

**Comment by siemvaessen** [comment]
Are the names in the file? And if yes, can they be added?

**Comment by kradoslavov** [comment]
Names of documents are still not in the data set

**Comment by kradoslavov** [comment]
Commitments are also not in the data set

**Comment by kradoslavov** [comment]
Commitments have been added

**Comment by siemvaessen** [comment]
done.

**Comment by kenek15** [comment]
Dear Siem,

The dataset has document titles:
<document-link format="application/pdf" url="http://www.unhabitat.org/downloads/docs/open_unhabitat_org/2009/ProjectBudget.pdf">
<category code="A05">Budget</category>
<title>Project Budget</title>
</document-link>
