### ISSUE TITLE
Whistle Blower

### ISSUE THREAD

**Issue by kenek15** [zimmerman-team/open-UN-Habitat#57]
Name and email should not be Mandatory
Not sure that it is picking the project title/id 
Email should be relayed to transparency@unhabitat.org

**Comment by siemvaessen** [comment]
Mark, do you have a solution for this? Please advise.

**Comment by markmn** [comment]
This are configured through the backend of the plugin, you can specify to have them required or not, so enusre they are not ticked as required and the email field to send the email to is set as above

**Comment by markmn** [comment]
For the project id and title, you would need to change the plugin to pick the title and id

**Comment by siemvaessen** [comment]
ok, this is very non OIPA specific. @kenek15 : could you ask Verviant to fix this.

**Comment by siemvaessen** [comment]
related to #57
