### ISSUE TITLE
Projects: Daily Update

### ISSUE THREAD

**Issue by kenek15** [zimmerman-team/open-UN-Habitat#59]
Does not seem to work, please confirm. 
This is the location of the XML: http://www.unhabitat.org/downloads/docs/open_unhabitat_org/UN-habitat_projects.xml

**Comment by Hedde** [comment]
Just a note from a semantical perspective; The XML provided at that link is invalid and cannot be parsed. A value field on a transaction requires a value-date, e.g.:

<value iso-date="2012-01-01">250000</value>
