### ISSUE TITLE
Contact form style issue

### ISSUE THREAD

**Issue by siemvaessen** [zimmerman-team/open-UN-Habitat#60]
Hi Mark,

http://open.unhabitat.org/contact/#cuform

&

http://staging.verviant.com/concepts/Open-UNH/Wordpress/?page_id=32

seem a bit different. We did however use your modified plugin.

Please advise,

Siem

**Comment by markmn** [comment]
Cant view the link on http://open.unhabitat.org/contact/#cuform

 Regards

Mark Mwongela

Managing Director

Verviant Consulting Services

Web, Software and Mobile Development

Joomla, Wordpress, .NET , PHP, Iphone, Blackberry, JAVA, C++ Development

 http://www.verviant.com/ http://www.verviant.com,  http://www.verviant.com/portfolio http://www.verviant.com/portfolio

Telephone : +254 (0)20 2124722 | +254 735444635

Website: www.verviant.com

**Comment by siemvaessen** [comment]
Mark, please advise.

**Comment by markmn** [comment]
We need to change the contact us page from the WP-Admin interface, to ensure they actually look similar. If we can get temporary access to wp-admin (through email that is)

**Comment by siemvaessen** [comment]
fixed
