### ISSUE TITLE
Whistle Blower

### ISSUE THREAD

**Issue by kenek15** [zimmerman-team/open-UN-Habitat#67]
We are not receiving emails from the online form just did a test and it does not work.

**Comment by siemvaessen** [comment]
Mark, could you check this?

**Comment by markmn** [comment]
Hey Siem,
We noted that the plugin files are different from those that are at staging/we had sent earlier, so we need to agree if we will change the files (that means restriction on updating these plugins but we achieve the look and the functionality required

Current: http://open.unhabitat.org/whistle-blower/
Staging: http://staging.verviant.com/concepts/Open-UNH/Wordpress/?page_id=42

Please advice

**Comment by markmn** [comment]
We have updated the settings, the email was missing, made a few changes to the styling from the plugin configs,should be working, 'cept the overall look (challenge as mentioned above)

**Comment by siemvaessen** [comment]
Hi Mark,

I believe I did update & test them.

In order to avoid confusion, I advise you push it to Github. Please note we can not update this plugin once we start using this modified version.

Thanks, Siem

**Comment by markmn** [comment]
With the plugins, we took a trade-off of updating against ensuring XHTML Validation, as well as styling, let's see how it goes.
We have updated configs in admin, it should send emails

**Comment by kenek15** [comment]
Still I do not get the messages, did a test half an hour ago
