### ISSUE TITLE
Make country page dynamic

### ISSUE THREAD

**Issue by siemvaessen** [zimmerman-team/open-UN-Habitat#68]
http://open.unhabitat.org/where-the-projects-are-found/?type=cn

is currently static. Needs to be connected to OIPA.

**Comment by kradoslavov** [comment]
Fixed in latest GitHub version

**Comment by siemvaessen** [comment]
A: Is the filter on the left side working? Seems to be non-responsive.
B: is the piechart built automatically?

**Comment by kradoslavov** [comment]
A: Fixed
B: Yes
