### ISSUE TITLE
Subject summary page

### ISSUE THREAD

**Issue by siemvaessen** [zimmerman-team/open-UN-Habitat#69]
http://open.unhabitat.org/which-sections-are-covered/?type=sc

is static & should be connected to OIPA.

**Comment by kradoslavov** [comment]
Fixed in latest GitHub version

**Comment by siemvaessen** [comment]
A: Is the filter on the left side working? Seems to be non-responsive.
B: is the piechart built automatically?

**Comment by kradoslavov** [comment]
A: Fixed
B: Yes
