### ISSUE TITLE
Wrap up visualisation page

### ISSUE THREAD

**Issue by siemvaessen** [zimmerman-team/open-UN-Habitat#70]
http://open.unhabitat.org/visualisation/

Should be updated once DAC codes ar available in OIPA. Please see: http://beta.openaid.nl/2012/01/30/bubbletree-visualisation/?lang=nl for example. It has top sectors (DAC) and then the subsector codes coming in from IATI.

Also: add currency

**Comment by kradoslavov** [comment]
Not sure if the DAC code are available and how to obtain the subsector codes

**Comment by siemvaessen** [comment]
We need proper sector codes etc in order to make this work. To wrap this up as part of phase 1 I suggest we add a deadline here: please provide those details before 5th of October.
